name: gomine_food
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  cached_network_image: ^3.2.3
  shimmer: ^3.0.0
  path_provider: ^2.0.15
  pdf: ^3.10.4
  open_file: ^3.3.2
  permission_handler: ^11.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

# Configuration for flutter_launcher_icons
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "lib/assets/logos.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  adaptive_icon_background: "#FFFFFF" # only for Android 8.0+
  adaptive_icon_foreground: "lib/assets/logos.png" # only for Android 8.0+
  remove_alpha_ios: true

flutter:
  uses-material-design: true
  assets:
    - lib/assets/